// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKQr3kr4525WnEdy9NVVwijpqAkxplNNQ',
    appId: '1:1096650159444:web:dd6639eacdb1d3c45484c1',
    messagingSenderId: '1096650159444',
    projectId: 'fir-flutter-codelab-d59b0',
    authDomain: 'fir-flutter-codelab-d59b0.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-d59b0.appspot.com',
    measurementId: 'G-V0SEB5ELRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbDruM1xjebtNyEzYl6qrRuI6eCUpfUq0',
    appId: '1:1096650159444:android:78b416ab6abd4e115484c1',
    messagingSenderId: '1096650159444',
    projectId: 'fir-flutter-codelab-d59b0',
    storageBucket: 'fir-flutter-codelab-d59b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChHu01nI9iCuB3KXsTdz9hSnBWxqIGqqg',
    appId: '1:1096650159444:ios:8448e26e3c5191115484c1',
    messagingSenderId: '1096650159444',
    projectId: 'fir-flutter-codelab-d59b0',
    storageBucket: 'fir-flutter-codelab-d59b0.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChHu01nI9iCuB3KXsTdz9hSnBWxqIGqqg',
    appId: '1:1096650159444:ios:b4244fb715fdb5f55484c1',
    messagingSenderId: '1096650159444',
    projectId: 'fir-flutter-codelab-d59b0',
    storageBucket: 'fir-flutter-codelab-d59b0.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
